---
# Source: xposer/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: xposer
    group: com.stakater.platform
    provider: stakater
    version: v0.0.20
    chart: "xposer-v0.0.20"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: xposer
data:
  config.yaml: |-
    domain: stakater.com
    ingressURLTemplate: "{{.Service}}.{{.Namespace}}.{{.Domain}}"
    ingressURLPath: /
    ingressNameTemplate: "{{.Service}}"
    tls: false
    tlsSecretNameTemplate: NO_SECRET
  default-url : default.com 
