---
# Source: xposer/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: xposer
    group: com.stakater.platform
    provider: stakater
    version: v0.0.9
    chart: "xposer-v0.0.9"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: xposer
data:
  config.yaml: |-
    domain: stakater.com
    ingressURLTemplate: ".."
    ingressURLPath: /
    ingressNameTemplate: ""
    tls: false
