---
# Source: chowkidar/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    configmap.reloader.stakater.com/reload: chowkidar
  labels:
    app: chowkidar
    group: com.stakater.platform
    provider: stakater
    version: 0.0.28
    chart: "chowkidar-0.0.28"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: chowkidar
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: chowkidar
      group: com.stakater.platform
      provider: stakater
  template:
    metadata:
      labels:
        app: chowkidar
        group: com.stakater.platform
        provider: stakater
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_FILE_PATH
          value: /configs/config.yaml
        image: "stakater/chowkidar:0.0.28"
        imagePullPolicy: IfNotPresent
        name: chowkidar
        volumeMounts:
        - mountPath: /configs
          name: config-volume
      serviceAccountName: chowkidar
      volumes:
      - configMap:
          name: chowkidar
        name: config-volume
              
