---
# Source: xposer/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    configmap.reloader.stakater.com/reload: xposer
  labels:
    app: xposer
    group: com.stakater.platform
    provider: stakater
    version: v0.0.18
    chart: "xposer-v0.0.18"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: xposer
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: xposer
      group: com.stakater.platform
      provider: stakater
  template:
    metadata:
      labels:
        app: xposer
        group: com.stakater.platform
        provider: stakater
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_FILE_PATH
          value: /configs/config.yaml
        image: "stakater/xposer:v0.0.18"
        imagePullPolicy: IfNotPresent
        name: xposer
        volumeMounts:
        - mountPath: /configs
          name: config-volume
      serviceAccountName: xposer
      volumes:
      - configMap:
          name: xposer
        name: config-volume
              
