---
# Source: chowkidar/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: chowkidar
    group: com.stakater.platform
    provider: stakater
    version: 0.0.28
    chart: "chowkidar-0.0.28"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: chowkidar
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels: 
    app: chowkidar
    group: com.stakater.platform
    provider: stakater
    version: 0.0.28
    chart: "chowkidar-0.0.28"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: chowkidar-role
rules:
  - apiGroups:
      - ""
    resources:      
      - pods
    verbs:
      - list
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels: 
    app: chowkidar
    group: com.stakater.platform
    provider: stakater
    version: 0.0.28
    chart: "chowkidar-0.0.28"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: chowkidar-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chowkidar-role
subjects:
  - kind: ServiceAccount
    name: chowkidar
    namespace: tools

