---
# Source: xposer/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: xposer
    group: com.stakater.platform
    provider: stakater
    version: v0.0.18
    chart: "xposer-v0.0.18"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: xposer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels: 
    app: xposer
    group: com.stakater.platform
    provider: stakater
    version: v0.0.18
    chart: "xposer-v0.0.18"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: xposer-role
rules:
  - apiGroups:
      - ""
      - "extensions"
      - "route.openshift.io"
    resources:
      - ingresses
      - routes
    verbs:
      - list
      - get
      - create
      - update
      - patch
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - list
      - get
      - watch
---
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels: 
    app: xposer
    group: com.stakater.platform
    provider: stakater
    version: v0.0.18
    chart: "xposer-v0.0.18"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: xposer-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: xposer-role
subjects:
  - kind: ServiceAccount
    name: xposer
    namespace: default
---
---
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels: 
    app: xposer
    group: com.stakater.platform
    provider: stakater
    version: v0.0.18
    chart: "xposer-v0.0.18"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: xposer-configmap-role-default
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
      - get
      - create
      - update
      - patch
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - list
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels: 
    app: xposer
    group: com.stakater.platform
    provider: stakater
    version: v0.0.18
    chart: "xposer-v0.0.18"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: xposer-configmap-role-binding-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: xposer-configmap-role-default
subjects:
  - kind: ServiceAccount
    name: xposer
    namespace: default
---
