apiVersion: v1
kind: ConfigMap
metadata:
  labels:
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
  name: {{ template "name" . }}
data:
  config.yaml: |-
    domain: {{ .Values.xposer.config.domain }}
    ingressURLTemplate: {{ .Values.xposer.config.ingressURLTemplate | quote }}
    ingressURLPath: {{ .Values.xposer.config.ingressURLPath }}
    ingressNameTemplate: {{ .Values.xposer.config.ingressNameTemplate | quote }}
    tls: {{ .Values.xposer.config.tls }}