apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    configmap.reloader.stakater.com/reload: {{ template "name" . }}
  labels:
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
  name: {{ template "name" . }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
{{ include "labels.selector" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "labels.selector" . | indent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_FILE_PATH
          value: {{ .Values.xposer.configFilePath }}
        image: "{{ .Values.xposer.image.name }}:{{ .Values.xposer.image.tag }}"
        imagePullPolicy: {{ .Values.xposer.image.pullPolicy }}
        name: {{ template "name" . }}
        volumeMounts:
        - mountPath: /configs
          name: config-volume
      serviceAccountName: {{ template "name" . }}
      volumes:
      - configMap:
          name: {{ template "name" . }}
        name: config-volume
              