apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "xposer-labels.stakater" . | indent 4 }}
{{ include "xposer-labels.chart" . | indent 4 }}
  name: {{ template "xposer-name" . }}
---
{{- if eq .Values.xposer.watchGlobally false }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels: 
{{ include "xposer-labels.stakater" . | indent 4 }}
{{ include "xposer-labels.chart" . | indent 4 }}
  name: {{ template "xposer-name" . }}-role
rules:
  - apiGroups:
      - ""
      - "extensions"
      - "route.openshift.io"
    resources:
      - ingresses
      - routes
    verbs:
      - list
      - get
      - create
      - update
      - patch
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - list
      - get
      - watch
{{- end }}
---
{{- if .Values.xposer.watchGlobally }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels: 
{{ include "xposer-labels.stakater" . | indent 4 }}
{{ include "xposer-labels.chart" . | indent 4 }}
  name: {{ template "xposer-name" . }}-role
rules:
  - apiGroups:
      - ""
      - "extensions"
      - "route.openshift.io"
    resources:
      - ingresses
      - routes
    verbs:
      - list
      - get
      - create
      - update
      - patch
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - list
      - get
      - watch
{{- end }}
---
{{- if eq .Values.xposer.watchGlobally false }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels: 
{{ include "xposer-labels.stakater" . | indent 4 }}
{{ include "xposer-labels.chart" . | indent 4 }}
  name: {{ template "xposer-name" . }}-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "xposer-name" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ template "xposer-name" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
---
{{- if .Values.xposer.watchGlobally }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels: 
{{ include "xposer-labels.stakater" . | indent 4 }}
{{ include "xposer-labels.chart" . | indent 4 }}
  name: {{ template "xposer-name" . }}-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "xposer-name" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ template "xposer-name" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
---
{{- if eq .Values.xposer.exposeServiceURL "globally"}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels: 
{{ include "xposer-labels.stakater" . | indent 4 }}
{{ include "xposer-labels.chart" . | indent 4 }}
  name: {{ template "xposer-name" . }}-configmap-role-{{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
      - get
      - create
      - update
      - patch
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - list
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels: 
{{ include "xposer-labels.stakater" . | indent 4 }}
{{ include "xposer-labels.chart" . | indent 4 }}
  name: {{ template "xposer-name" . }}-configmap-role-binding-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "xposer-name" . }}-configmap-role-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ template "xposer-name" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
---
{{- if eq .Values.xposer.exposeServiceURL "locally" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels: 
{{ include "xposer-labels.stakater" . | indent 4 }}
{{ include "xposer-labels.chart" . | indent 4 }}
  name: {{ template "xposer-name" . }}-configmap-role-{{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
      - get
      - create
      - update
      - patch
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - list
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels: 
{{ include "xposer-labels.stakater" . | indent 4 }}
{{ include "xposer-labels.chart" . | indent 4 }}
  name: {{ template "xposer-name" . }}-configmap-role-binding-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "xposer-name" . }}-configmap-role-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ template "xposer-name" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
---